name: Build & Test Debug

on:
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]

concurrency:
  group: integration-tests-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false && github.actor != 'FrontierATC' # Frontier
    runs-on: ubuntu-latest
    name: Build Client & Server
    outputs:
      test-list: ${{ steps.listtests.outputs.tests }}

    steps:
      # Make sure we check out the exact SHA that started the flow, so we don't test someone elses code
    - name: Checkout Master
      uses: actions/checkout@v7
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        submodules: recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m

    # This takes all the test namespaces and puts them into the output so we can run multiple jobs for the tests at once
    - name: List all Tests
      id: listtests
      run: |
        echo "tests=$(dotnet test  --no-build Content.IntegrationTests/Content.IntegrationTests.csproj \
        --list-tests -- NUnit.DisplayName=FullName \
        | grep -E "^[[:space:]]+[A-Za-z0-9_]+\." \
        | sed 's/^[[:space:]]*//' \
        | awk -F. '{print $1"."$2"."$3"."$4}' \
        | sort -u | jq -R . | jq -s -c .)" >> "$GITHUB_OUTPUT"

    # Rather than re-building for every test, we store the built workspace and just share that between all the jobs
    - name: Cache Build Objects
      uses: actions/cache/save@v5
      with:
        path: bin
        key: build-pr-${{ github.event.pull_request.number }}

  # We have to checkout because the tests look for a bunch of local resources
  # But the cache means we don't have to re-build every time at least.
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    needs: build
    steps:
    - name: Checkout Master
      uses: actions/checkout@v7
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.100

    - name: Fetch Pre-Built Workspace
      id: fetch
      continue-on-error: true
      uses: actions/cache/restore@v5
      with:
        path: bin
        key: build-pr-${{ github.event.pull_request.number }}
        fail-on-cache-miss: true

    - name: Re-Build the files if the cached build is missing
      if: steps.fetch.outcome == 'failure'
      run: |
        dotnet restore
        dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m

    - name: Run Tests
      run: dotnet vstest ./bin/Content.Tests/Content.Tests.dll -- NUnit.ConsoleOut=0


  integrationtests:
    runs-on: ubuntu-latest
    needs: build
    name: Run Integration Tests
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        test: ${{ fromJson(needs.build.outputs.test-list) }}
    steps:
    - name: Checkout Master
      uses: actions/checkout@v7
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        submodules: recursive

    # Github sometimes gets a bit angry if ALL the jobs hit the cache at once, so staggering a little bit seems to make them start happier
    - name: Delay to stagger starts
      run: |
        DELAY=$((1 + RANDOM % 15))
        echo "Staggering for $DELAY seconds"
        sleep $DELAY

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.100

    - name: Fetch Pre-Built Workspace
      id: fetch
      continue-on-error: true
      uses: actions/cache/restore@v5
      with:
        path: bin
        key: build-pr-${{ github.event.pull_request.number }}
        fail-on-cache-miss: true

    - name: Re-Build the files if the cached build is missing
      if: steps.fetch.outcome == 'failure'
      run: |
        dotnet restore
        dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m

    - name: Run Integration Tests
      continue-on-error: true
      id: integrationtestrun
      env:
        DOTNET_GCHighMemPercent: 75
      run: |
        dotnet test ./bin/Content.IntegrationTests/Content.IntegrationTests.dll \
        --logger "console;verbosity=normal" \
        --filter "FullyQualifiedName~${{ matrix.test }}" -- \
        NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed

    # For some reason, the github runners just randomly crash
    # If they do, re-run the tests and slow things down a bit
    # But also upload the crash dump as an artifact in-case things are really broken.
    - name: Re-Run Integration Tests on failure
      if: steps.integrationtestrun.outcome == 'failure'
      env:
        DOTNET_gcServer: 0
        DOTNET_GCHighMemPercent: 75
        ROBUST_TEST_THREADS: 2
      run: |
        dotnet test ./bin/Content.IntegrationTests/Content.IntegrationTests.dll \
        --logger "console;verbosity=normal" \
        --blame-crash --blame-crash-dump-type mini \
        --filter "FullyQualifiedName~${{ matrix.test }}" -- \
        MaxCpuCount=1 NUnit.NumberOfTestWorkers=1 NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed

    - name: Upload Crash Dump
      if: failure() && steps.integrationtestrun.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: crash-dump-${{matrix.test}}
        retention-days: 3
        path: |
          **/TestResults/**/*.xml
          **/TestResults/**/*.dmp

  ci-success:
    name: Testing Success
    needs:
      - tests
      - integrationtests
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
