name: "Labels: PR"

concurrency:
  group: labels
  cancel-in-progress: false
  queue: max

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'PJBot' && github.actor != 'xemeraldwingx-dot' # Hardlight
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6.1.0
